# -*- coding: utf-8 -*-
"""MohanUpdated_file_MSc_supervisor_fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VU0YdtTQ4nIya1EdUa8pfDwuAPx0Vl88
"""

#  Import Required Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, learning_curve, GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

from prophet import Prophet

import warnings
warnings.filterwarnings("ignore")

# -------------------------------
# Load Dataset
# -------------------------------

df = pd.read_csv("household_power_consumption.txt",
                 sep=';',
                 parse_dates={'DateTime':['Date','Time']},
                 infer_datetime_format=True,
                 low_memory=False,
                 na_values=['?'])

df.head()

df.shape

# -------------------------------
# Data Cleaning
# -------------------------------

# Convert numeric columns
numeric_cols = ['Global_active_power','Global_reactive_power','Voltage',
                'Sub_metering_1','Sub_metering_2','Sub_metering_3']

df[numeric_cols] = df[numeric_cols].astype(float)

# Drop missing values
df.dropna(inplace=True)

# Set datetime index
df.set_index('DateTime', inplace=True)

df.head()

# -------------------------------
# Resample to hourly data
# -------------------------------

df_hourly = df.resample('H').mean()
df_hourly = df_hourly.dropna()

df_hourly.head()

# -------------------------------
#  Feature Engineering
# -------------------------------

df_hourly['hour'] = df_hourly.index.hour
df_hourly['dayofweek'] = df_hourly.index.dayofweek

# Lag features
df_hourly['lag1'] = df_hourly['Global_active_power'].shift(1)
df_hourly['lag24'] = df_hourly['Global_active_power'].shift(24)

# Rolling mean
df_hourly['rolling_24'] = df_hourly['Global_active_power'].rolling(window=24).mean()

df_hourly.dropna(inplace=True)

df_hourly.head()

# -------------------------------------------------------
# Time-Series Plot of Global Active Power
# -------------------------------------------------------

plt.figure(figsize=(15,4))
plt.plot(df_hourly['Global_active_power'], color='blue')
plt.title("Global Active Power (Hourly) - First Look", fontsize=14)
plt.xlabel("Time")
plt.ylabel("kW")
plt.show()

# -------------------------------------------------------
# Distribution of Global Active Power
# -------------------------------------------------------

plt.figure(figsize=(8,5))
sns.histplot(df_hourly['Global_active_power'], kde=True, bins=50)
plt.title("Distribution of Global Active Power", fontsize=14)
plt.xlabel("Global Active Power (kW)")
plt.ylabel("Frequency")
plt.show()

# -------------------------------------------------------
# Average Usage by Hour
# -------------------------------------------------------

plt.figure(figsize=(10,5))
df_hourly.groupby(df_hourly.index.hour)['Global_active_power'].mean().plot()
plt.title("Average Power Usage by Hour of Day", fontsize=14)
plt.xlabel("Hour")
plt.ylabel("Average kW")
plt.grid(True)
plt.show()

# -------------------------------------------------------
# Average Usage by Day of Week
# -------------------------------------------------------

plt.figure(figsize=(10,5))
df_hourly.groupby(df_hourly.index.dayofweek)['Global_active_power'].mean().plot(kind='bar')
plt.title("Average Power Usage by Day of Week", fontsize=14)
plt.xlabel("Day of Week (0 = Monday)")
plt.ylabel("Average kW")
plt.show()

# -------------------------------------------------------
# L-Shaped Correlation Heatmap
# -------------------------------------------------------

plt.figure(figsize=(12,6))

corr_cols = ['Global_active_power','Global_reactive_power','Voltage',
             'Sub_metering_1','Sub_metering_2','Sub_metering_3',
             'hour','dayofweek','lag1','lag24','rolling_24']

corr = df_hourly[corr_cols].corr()

# Create mask for L-shape (upper triangle mask)
mask = np.triu(np.ones_like(corr, dtype=bool))

sns.heatmap(
    corr,
    mask=mask,
    annot=True,
    cmap='coolwarm',
    center=0,
    vmin=-1,
    vmax=1,
    fmt=".2f",
    linewidths=0.5
)

plt.title("Correlation Heatmap After Feature Engineering (L-Shape)", fontsize=14)
plt.show()

# -------------------------------------------------------
#  Time-Series Train/Test Split (No Shuffle)
# -------------------------------------------------------

# Define target and features
target = 'Global_active_power'

feature_cols = ['Global_reactive_power','Voltage',
                'Sub_metering_1','Sub_metering_2','Sub_metering_3',
                'hour','dayofweek','lag1','lag24','rolling_24']

X = df_hourly[feature_cols]
y = df_hourly[target]

# Time-series split: 80% train, 20% test
split_point = int(len(df_hourly) * 0.8)

X_train = X.iloc[:split_point]
X_test  = X.iloc[split_point:]

y_train = y.iloc[:split_point]
y_test  = y.iloc[split_point:]

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("Train start:", X_train.index.min(), "→ Train end:", X_train.index.max())
print("Test start:", X_test.index.min(),   "→ Test end:", X_test.index.max())

X_train.shape, X_test.shape, y_train.shape, y_test.shape

# Hyperparameter Tuning for Random Forest
param_grid = {
    'n_estimators':[100,200],
    'max_depth':[10,15,20]
}
grid = GridSearchCV(RandomForestRegressor(random_state=42), param_grid, cv=3, scoring='neg_mean_squared_error', n_jobs=-1)
grid.fit(X_train, y_train)
print('Best Parameters:', grid.best_params_)
rf_model = grid.best_estimator_

# -------------------------------------------------------
# Train RandomForest Model
# -------------------------------------------------------

rf_model = RandomForestRegressor(
    n_estimators=200,
    max_depth=15,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

print("RandomForest model trained successfully!")

# -------------------------------------------------------
# Evaluation Metrics (RMSE, MAE)
# -------------------------------------------------------

rf_preds = rf_model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, rf_preds))
mae = mean_absolute_error(y_test, rf_preds)

print("RandomForest Performance:")
print("--------------------------")
print("RMSE:", rmse)
print("MAE :", mae)

# -------------------------------------------------------
# Prediction vs Actual Plot
# -------------------------------------------------------

plt.figure(figsize=(15,5))
plt.plot(y_test.index, y_test, label='Actual', color='black', linewidth=1)
plt.plot(y_test.index, rf_preds, label='Predicted', color='red', linewidth=0.8, alpha=0.6)

plt.title("RandomForest: Actual vs Predicted Energy Usage", fontsize=14)
plt.ylabel("Global Active Power (kW)")
plt.xlabel("Time")
plt.legend()
plt.show()

# -------------------------------------------------------
# Learning Curve for RandomForest
# -------------------------------------------------------

train_sizes, train_scores, test_scores = learning_curve(
    estimator=rf_model,
    X=X_train,
    y=y_train,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 6)
)

train_mean = -train_scores.mean(axis=1)
test_mean = -test_scores.mean(axis=1)

plt.figure(figsize=(10,5))
plt.plot(train_sizes, train_mean, 'o-', label="Training Error")
plt.plot(train_sizes, test_mean, 'o-', label="Validation Error")

plt.grid(True, alpha=0.3)
plt.title("Learning Curve - RandomForest", fontsize=14)
plt.xlabel("Training Samples")
plt.ylabel("MSE")
plt.legend()
plt.show()

# -------------------------------------------------------
# CELL 16: Train XGBoost Model
# -------------------------------------------------------

xgb_model = XGBRegressor(
    n_estimators=300,
    max_depth=10,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

print("XGBoost model trained successfully!")

# -------------------------------------------------------
# XGBoost Evaluation (RMSE, MAE)
# -------------------------------------------------------

xgb_preds = xgb_model.predict(X_test)

rmse_xgb = np.sqrt(mean_squared_error(y_test, xgb_preds))
mae_xgb = mean_absolute_error(y_test, xgb_preds)

print("XGBoost Performance:")
print("----------------------")
print("RMSE:", rmse_xgb)
print("MAE :", mae_xgb)

# -------------------------------------------------------
# XGBoost Predictions vs Actual
# -------------------------------------------------------

plt.figure(figsize=(15,5))
plt.plot(y_test.index, y_test, label='Actual', color='black', linewidth=1)
plt.plot(y_test.index, xgb_preds, label='Predicted (XGBoost)', color='green', linewidth=0.8, alpha=0.6)

plt.title("XGBoost: Actual vs Predicted Energy Usage", fontsize=14)
plt.ylabel("Global Active Power (kW)")
plt.xlabel("Time")
plt.legend()
plt.show()

# -------------------------------------------------------
# XGBoost Feature Importance
# -------------------------------------------------------

importances = pd.Series(xgb_model.feature_importances_, index=X_train.columns)
importances = importances.sort_values()

plt.figure(figsize=(10,6))
importances.plot(kind='barh')
plt.title("XGBoost Feature Importance", fontsize=14)
plt.xlabel("Importance Score")
plt.show()

# -------------------------------------------------------
# Learning Curve - XGBoost
# -------------------------------------------------------

train_sizes, train_scores, test_scores = learning_curve(
    estimator=xgb_model,
    X=X_train,
    y=y_train,
    cv=5,
    scoring='neg_mean_squared_error',
    n_jobs=-1,
    train_sizes=np.linspace(0.1, 1.0, 6)
)

train_mean = -train_scores.mean(axis=1)
test_mean = -test_scores.mean(axis=1)

plt.figure(figsize=(10,5))
plt.plot(train_sizes, train_mean, 'o-', label="Training Error")
plt.plot(train_sizes, test_mean, 'o-', label="Validation Error")
plt.grid(True, alpha=0.3)
plt.title("Learning Curve - XGBoost", fontsize=14)
plt.xlabel("Training Samples")
plt.ylabel("MSE")
plt.legend()
plt.show()

# -------------------------------------------------------
#  Prepare Data for Prophet
# -------------------------------------------------------

prophet_df = df_hourly.reset_index()[['DateTime','Global_active_power']]

prophet_df.columns = ['ds','y']

prophet_df.head()

# -------------------------------------------------------
#  Train Prophet Model
# -------------------------------------------------------

prophet_model = Prophet(
    daily_seasonality=True,
    weekly_seasonality=True,
    yearly_seasonality=True
)

prophet_model.fit(prophet_df)

print("Prophet model trained successfully!")

# -------------------------------------------------------
# Create Future Dataframe
# -------------------------------------------------------

future = prophet_model.make_future_dataframe(periods=168, freq='H')

future.tail()

# -------------------------------------------------------
# Prophet Forecast
# -------------------------------------------------------

forecast = prophet_model.predict(future)

forecast[['ds','yhat','yhat_lower','yhat_upper']].tail()

# -------------------------------------------------------
# Prophet Forecast Plot
# -------------------------------------------------------

fig = prophet_model.plot(forecast)

plt.title("Prophet Forecast for Energy Consumption", fontsize=14)
plt.xlabel("Date")
plt.ylabel("Global Active Power (kW)")
plt.show()

# -------------------------------------------------------
# Prophet Components
# -------------------------------------------------------

prophet_model.plot_components(forecast)
plt.show()

# -------------------------------------------------------
# Prophet Evaluation
# -------------------------------------------------------

prophet_test = forecast.set_index('ds').loc[y_test.index]

rmse_prophet = np.sqrt(mean_squared_error(y_test, prophet_test['yhat']))
mae_prophet = mean_absolute_error(y_test, prophet_test['yhat'])

print("Prophet Performance:")
print("--------------------")
print("RMSE:", rmse_prophet)
print("MAE :", mae_prophet)

# -------------------------------------------------------
# Model Performance Comparison
# -------------------------------------------------------

models = ['RandomForest','XGBoost','Prophet']

rmse_values = [	0.2458, 0.2433, 0.6285]
mae_values  = [0.1606, 0.1578, 0.4791
]

comparison_df = pd.DataFrame({
    'Model': models,
    'RMSE': rmse_values,
    'MAE': mae_values
})

comparison_df

plt.figure(figsize=(10,5))

x = np.arange(len(models))
width = 0.35

plt.bar(x - width/2, rmse_values, width, label='RMSE')
plt.bar(x + width/2, mae_values, width, label='MAE')

plt.xticks(x, models)
plt.title("Model Performance Comparison")
plt.ylabel("Error")
plt.legend()

plt.show()

# -------------------------------------------------------
# Rolling Statistics for Anomaly Detection
# -------------------------------------------------------

window = 24   # 24 hours window

df_hourly['rolling_mean'] = df_hourly['Global_active_power'].rolling(window).mean()
df_hourly['rolling_std'] = df_hourly['Global_active_power'].rolling(window).std()

df_hourly.dropna(inplace=True)

df_hourly.head()

# -------------------------------------------------------
# Z-Score Calculation
# -------------------------------------------------------

df_hourly['z_score'] = (
    (df_hourly['Global_active_power'] - df_hourly['rolling_mean']) /
    df_hourly['rolling_std']
)

df_hourly.head()

# -------------------------------------------------------
# Detect Anomalies
# -------------------------------------------------------

threshold = 3

df_hourly['z_anomaly'] = np.where(abs(df_hourly['z_score']) > threshold, 1, 0)

print("Number of anomalies detected:", df_hourly['z_anomaly'].sum())

# -------------------------------------------------------
# Plot Z-Score Anomalies
# -------------------------------------------------------

plt.figure(figsize=(15,5))

plt.plot(df_hourly.index, df_hourly['Global_active_power'], label='Energy Usage')

anomalies = df_hourly[df_hourly['z_anomaly'] == 1]

plt.scatter(anomalies.index,
            anomalies['Global_active_power'],
            color='red',
            label='Anomaly')

plt.title("Anomaly Detection using Rolling Z-Score")
plt.xlabel("Time")
plt.ylabel("Global Active Power (kW)")
plt.legend()

plt.show()

from sklearn.ensemble import IsolationForest

# -------------------------------------------------------
# Features for Isolation Forest
# -------------------------------------------------------

iso_features = df_hourly[['Global_active_power',
                          'Voltage',
                          'Global_intensity',
                          'Sub_metering_1',
                          'Sub_metering_2',
                          'Sub_metering_3']]

iso_features.head()

# -------------------------------------------------------
# Train Isolation Forest
# -------------------------------------------------------

iso_model = IsolationForest(
    n_estimators=200,
    contamination=0.01,
    random_state=42
)

df_hourly['iso_anomaly'] = iso_model.fit_predict(iso_features)

df_hourly['iso_anomaly'] = df_hourly['iso_anomaly'].map({1:0, -1:1})

print("Isolation Forest anomalies:", df_hourly['iso_anomaly'].sum())

plt.figure(figsize=(15,5))

plt.plot(df_hourly.index, df_hourly['Global_active_power'], label='Energy Usage')

iso_anomalies = df_hourly[df_hourly['iso_anomaly'] == 1]

plt.scatter(iso_anomalies.index,
            iso_anomalies['Global_active_power'],
            color='purple',
            label='Isolation Forest Anomaly')

plt.title("Anomaly Detection using Isolation Forest")
plt.xlabel("Time")
plt.ylabel("Global Active Power (kW)")
plt.legend()

plt.show()

# -------------------------------------------------------
# Prophet Residual Calculation
# -------------------------------------------------------

prophet_results = forecast.set_index('ds')

df_hourly['prophet_pred'] = prophet_results.loc[df_hourly.index]['yhat']

df_hourly['residual'] = df_hourly['Global_active_power'] - df_hourly['prophet_pred']

df_hourly.head()

# -------------------------------------------------------
# Prophet Residual Z-Score
# -------------------------------------------------------

residual_mean = df_hourly['residual'].mean()
residual_std = df_hourly['residual'].std()

df_hourly['residual_zscore'] = (
    (df_hourly['residual'] - residual_mean) / residual_std
)

threshold = 3

df_hourly['prophet_anomaly'] = np.where(abs(df_hourly['residual_zscore']) > threshold, 1, 0)

print("Prophet anomalies:", df_hourly['prophet_anomaly'].sum())

plt.figure(figsize=(15,5))

plt.plot(df_hourly.index, df_hourly['Global_active_power'], label='Energy Usage')

prophet_anomalies = df_hourly[df_hourly['prophet_anomaly'] == 1]

plt.scatter(prophet_anomalies.index,
            prophet_anomalies['Global_active_power'],
            color='orange',
            label='Prophet Residual Anomaly')

plt.title("Anomaly Detection using Prophet Residuals")
plt.xlabel("Time")
plt.ylabel("Global Active Power (kW)")
plt.legend()

plt.show()

# -------------------------------------------------------
# Anomaly Detection Comparison
# -------------------------------------------------------

methods = ['Z-Score','Isolation Forest','Prophet Residual']

counts = [273,342,413]

plt.figure(figsize=(8,5))

plt.bar(methods, counts)

plt.title("Comparison of Anomaly Detection Methods")
plt.ylabel("Number of Detected Anomalies")

plt.show()